### ISSUE TITLE
Meanings of the Columns in .cdtraj

### ISSUE THREAD

**Issue by lin1881127** [Bigscity-VecCity/VecCity#1]
![屏幕截图 2024-12-17 204225](https://github.com/user-attachments/assets/2aa5fd95-bd2d-46fe-8fbf-b6c796db168f)

How to understand the different meanings represented by these words

**Comment by ShotDownDiane** [comment]
There is a relationship as follows: each line represents a dynamic record, and several records together compose a trajectory in chronological order.
* dyna_id: the unique ID of a dynamic record.
* traj_id: the unique ID of a trajectory.
* time: the timestamp of the dynamic record.
* type: indicates the type of the dynamic record, which can be either "trajectory" or "od".
* entity_id: identifies the user who generated this record.
* geo_id: identifies the corresponding map entity that the user visited.

This file is an older version, and we will update it soon to align with the paper and the README.
I sincerely apologize for any inconvenience this may have caused you.
